import { randomUUID } from "node:crypto";
import {
  runAgent,
  type ApprovalRequest,
  type ApprovalDecision,
} from "./agent-runner";
import {
  sessionStore,
  type SessionInputs,
  type DesignStudyInputs,
} from "./session-store";

// BUILD MARKER: printed on module load so you can verify the dev server
// is running the latest code. If you don't see this in your `bun run dev`
// terminal after a file save or restart, HMR is serving stale code.
const __FORGE_WORKER_BUILD =
  "2026-04-12 v0.1.3 phase-runner split (startWorker removed)";
console.log(`[forge worker] module loaded: ${__FORGE_WORKER_BUILD}`);

/**
 * worker.ts is now a *thin* module containing only:
 *
 *   1. The prompt builders used by every phase (plan-autoplan, init-app,
 *      seed-demo, feature-continue, resume). Prompt text is static and
 *      safe to share across phase-runner + resume paths.
 *   2. `startResumeWorker()` — the standalone `claude -c` resume flow.
 *      Resume is deliberately kept as a one-shot IIFE because it doesn't
 *      chain into other phases (it picks up mid-session and completes
 *      whatever was running). No HMR chain issues because it's a single
 *      request-bounded worker.
 *
 * Everything else — the multi-phase orchestration, per-phase IIFEs, build
 * verification subprocess runner, implementFeatures loop — moved to
 * `phase-runner.ts`. That module is imported by the `/run-phase` HTTP
 * route handler, so each phase runs in a fresh Next.js route-handler
 * context (HMR-safe).
 *
 * See `phase-runner.ts` module header for the architectural rationale.
 */

// ---------------------------------------------------------------------------
// Shared prompt preamble (file-read limit fallback guidance)
// ---------------------------------------------------------------------------

const FORGE_PROMPT_PREAMBLE = [
  "=== Forge session file-reading guidance ===",
  "",
  "Claude Code's Read tool has a hardcoded 10,000-token-per-call limit.",
  "Files that exceed it return an error like:",
  "  \"File content (12771 tokens) exceeds maximum allowed tokens (10000).\"",
  "",
  "When you hit this error, DO NOT stop or retry the same Read — the limit",
  "is per-call and hardcoded. Fall back IMMEDIATELY to one of these:",
  "",
  "- **Bash with line slicing**: `sed -n '1,200p' <file>` or",
  "  `awk 'NR>=100 && NR<=300' <file>` or `head -n 500 <file>`.",
  "- **Read with offset + limit**: `Read({ file_path, offset: 200, limit: 100 })`",
  "  chunks the file across multiple calls.",
  "- **Grep** (rg) for keyword search without reading the whole file.",
  "",
  "Files in this repo that commonly exceed the cap:",
  "  PLAN.md (after matrix fills up), LESSONS.md, CLAUDE.md,",
  "  long /feature continue spec files, web/prisma/schema.prisma,",
  "  and any JSONL conversation history under ~/.claude/projects/.",
  "",
  "Do not treat Read errors as failures. Try Bash. Continue the task.",
  "",
  "=== End file-reading guidance ===",
  "",
].join("\n");

// ---------------------------------------------------------------------------
// Prompt builders — exported for phase-runner.ts and startResumeWorker
// ---------------------------------------------------------------------------

export function buildPlanAutoplanPrompt(): string {
  // This prompt does NOT use the /plan-autoplan skill or its sub-skills.
  // In -p mode, invoking sub-skills via the Skill tool doesn't chain them
  // — each sub-skill reads its SKILL.md (which says "write your section
  // and stop, the orchestrator will continue") and the agent stops because
  // there's no separate orchestrator. This prompt inlines all five
  // reviewer roles so the agent executes them as a single continuous task.
  return FORGE_PROMPT_PREAMBLE + [
    "You are running a five-role planning review of the product described",
    "in `IDEA.md` at the repo root. You must execute ALL FIVE reviews in a",
    "SINGLE continuous conversation. Do NOT stop between reviewers. Do NOT",
    "wait for any external orchestrator. You are the orchestrator.",
    "",
    "## Ground rules",
    "",
    "- Read files only, write exactly one file: `PLAN_REVIEW.md` at the repo root.",
    "- Do NOT touch source files under `web/`, `mobile/`, or `specs/**`.",
    "- Do NOT run `bin/init.sh` or `rewrite-docs.sh`.",
    "- Do NOT use the `Skill` tool to invoke `/plan-ceo-review` etc. — ignore",
    "  those standalone skills entirely. Follow the inline guidance below.",
    "",
    "## Step 1 — Read the brief",
    "",
    "Read `IDEA.md` at the repo root. Absorb the product name, tagline,",
    "description, target user, MVP feature backlog, out-of-scope list,",
    "constraints, and open questions.",
    "",
    "## Step 2 — Create PLAN_REVIEW.md with the header",
    "",
    "Use the `Write` tool to create `PLAN_REVIEW.md` at the repo root with:",
    "",
    "```markdown",
    "# Plan review — <product name from IDEA.md>",
    "",
    "_Generated by Triplane Forge on <today's date>. Five reviewers: CEO,",
    "Engineering, Design, DevEx, QA._",
    "```",
    "",
    "## Step 3 — Append `## CEO review`",
    "",
    "Play a founder/CEO role. Push back where the brief is soft, cut what",
    "doesn't pay rent. Use the `Edit` tool to append a new `## CEO review`",
    "section to `PLAN_REVIEW.md` with these exact subsections:",
    "",
    "- **Sharper target user**: one sentence narrowing the brief's target to",
    "  a specific, testable user segment.",
    "- **The core hypothesis**: one sentence naming what has to be true for",
    "  this product to work. `<user> will <behavior> because <reason>.`",
    "- **Cut list (v0.1)**: bulleted list of features that should be deferred,",
    "  with one-line rationale each. Be stingy but decisive.",
    "- **What's missing**: 2–3 bullets on gaps — antagonist, failure modes,",
    "  monetization questions, required integrations.",
    "- **Product-market-fit readiness: N/10** with one-sentence justification.",
    "",
    "## Step 4 — Append `## Engineering review`",
    "",
    "Play an engineering manager role. Architect the build and name the",
    "load-bearing risks. Use `Edit` to append a `## Engineering review`",
    "section with:",
    "",
    "- **Surfaces in scope**: `Web: yes/no`, `Mobile (Android): yes/no`,",
    "  `Mobile (iOS): yes/no` — with a one-line scope per surface.",
    "- **Architecture sketch**: 3–6 bullets naming the concrete directories",
    "  that change (e.g., `web/src/app/api/v1/campaigns/route.ts`,",
    "  `mobile/shared/.../domain/campaigns/`). No code — paths and their",
    "  relationships only.",
    "- **Load-bearing risks**: 2–5 bullets. Each risk is one sentence that",
    "  identifies a decision that, if wrong, forces rework.",
    "- **Gotcha watchlist**: pull from `CLAUDE.md § Common gotchas`",
    "  (`String.format` JVM-only, iOS ObjC exporter crashes on public",
    "  composeApp types, Next.js 16 `await params`, etc.) — only list gotchas",
    "  this specific brief would trip. If none apply, write `_(none)_`.",
    "- **Test strategy**: what's worth unit testing, what's integration, what",
    "  defers to future `/qa`. Don't over-prescribe.",
    "- **Implementability: N/10** with one-sentence justification.",
    "",
    "## Step 5 — Append `## Design review`",
    "",
    "Play a design/UX role. Prose only — no mocks, no HTML, no Figma-speak.",
    "Use `Edit` to append a `## Design review` section with:",
    "",
    "- **Rubric table** (4 rows): Clarity / Discoverability / Delight /",
    "  Accessibility. Each scored 0–10 with one-line justification.",
    "- **Three interaction decisions**: the three choices that will most",
    "  shape the product's feel.",
    "- **One more cut**: name one feature you'd reluctantly cut for design",
    "  coherence.",
    "- **Design readiness: N/10** averaged from the rubric.",
    "",
    "## Step 6 — Append `## DevEx review`",
    "",
    "Play a developer-experience role. Imagine a new contributor cloning",
    "the downstream repo tomorrow. Use `Edit` to append a `## DevEx review`",
    "section with:",
    "",
    "- **Top 3 onboarding friction points** for the specific feature set.",
    "- **Recommended `README.md` additions**: 2–3 bullets referencing",
    "  existing Triplane commands and skills.",
    "- **Recommended `CLAUDE.md` additions**: 1–2 downstream-specific gotchas.",
    "- **Onboarding: N/10** justified by the clone → first feature shipped gap.",
    "",
    "## Step 7 — Append `## QA review`",
    "",
    "Play a plan-phase QA lead. The product doesn't exist yet — write the",
    "test rubric a future `/qa` run would execute against. Use `Edit` to",
    "append a `## QA review` section with:",
    "",
    '- _Opening italic note_: "Plan-phase scenarios. No browser automation',
    '  — the live-browser /qa skill is roadmap."',
    "- **Per-feature scenarios**: one `### <feature-name>` subsection per",
    "  post-cut-list MVP item. Golden path / Edge case 1 / Edge case 2, then",
    '  an Acceptance criterion in "A user can..." voice.',
    "- **Cross-feature risks**: 2–4 bullets.",
    "- **Regression watchlist (Triplane invariants)**: 3–4 bullets citing",
    "  architecture principles the product could quietly break.",
    "- **Testability: N/10**.",
    "",
    "## Step 8 — Append `## Next steps`",
    "",
    "Synthesize the top actions across all five reviews. Use `Edit` to",
    "append a `## Next steps` section with top three concrete actions,",
    "a recommended first command, and a per-reviewer score table.",
    "",
    "## Step 9 — Report done",
    "",
    "Print a 2–3 line summary to the chat. Name the `PLAN_REVIEW.md` path,",
    "the five reviewer scores, and the recommended next command.",
    "",
    "## Critical — do NOT stop early",
    "",
    "You MUST complete all nine steps in this single run. Do NOT stop after",
    "Step 3 or any intermediate step. Each `Edit` tool call returns quickly",
    "— that is your cue to move to the NEXT step, not to end the conversation.",
    "",
    "Start with Step 1 now.",
  ].join("\n");
}

export function buildInitAppPrompt(inputs: SessionInputs): string {
  const hasBrand = inputs.brandColor !== undefined;
  const brandTriple = hasBrand
    ? `${inputs.brandColor!.L},${inputs.brandColor!.C},${inputs.brandColor!.h}`
    : "";

  const step5Command = hasBrand
    ? [
        "When you reach Step 5, invoke `rewrite-docs.sh` with this EXACT command",
        "(it has been pre-filled with the user's inputs — do not modify any argument):",
        "",
        "```bash",
        "./.claude/skills/init-app/rewrite-docs.sh \\",
        `    --display-name "${inputs.displayName.replace(/"/g, '\\"')}" \\`,
        `    --slug ${inputs.slug} \\`,
        `    --brand-color "${brandTriple}" \\`,
        "    --yes",
        "```",
        "",
        "This writes the brand to `design/tokens.json` and runs `./bin/design-tokens.sh` to regenerate `web/src/app/generated/tokens.css` + `mobile/.../common/theme/DesignTokens.kt` with the new palette.",
      ].join("\n")
    : [
        "When you reach Step 5, invoke `rewrite-docs.sh` with this EXACT command",
        "(the user did NOT pick a brand color, so DO NOT pass `--brand-color`):",
        "",
        "```bash",
        "./.claude/skills/init-app/rewrite-docs.sh \\",
        `    --display-name "${inputs.displayName.replace(/"/g, '\\"')}" \\`,
        `    --slug ${inputs.slug} \\`,
        "    --yes",
        "```",
        "",
        "`design/tokens.json` stays at the default gray palette.",
      ].join("\n");

  return FORGE_PROMPT_PREAMBLE + [
    "Run /init-app to bootstrap this Triplane-template clone for the downstream project.",
    "",
    "`IDEA.md` is at the repo root. The user has already provided the Step 2 inputs via the Triplane Forge web UI — use these values directly and DO NOT pause to ask the user to confirm them:",
    "",
    `- Project slug:   ${inputs.slug}`,
    `- Java namespace: ${inputs.namespace}`,
    `- Display name:   ${inputs.displayName}`,
    hasBrand
      ? `- Brand color:    L=${inputs.brandColor!.L}, C=${inputs.brandColor!.C}, h=${inputs.brandColor!.h} (OKLch)`
      : "- Brand color:    not set",
    "",
    step5Command,
    "",
    "Execution notes specific to Triplane Forge:",
    "",
    "1. You are running in a git worktree on branch `forge-session-<id>` (not on `main`), so Step 1's branch safety check will pass.",
    "2. Do NOT pause for conversational approvals. Every Bash/Write/Edit call is routed through `canUseTool` and shown to the user as a forge approval dialog. That is their checkpoint mechanism; do not ask them twice.",
    "3. Run through the step sequence without stopping: Step 1 pre-flight → Step 2 (skip — inputs already provided) → Step 3 execution plan (just state it in text and move on) → Step 4 `bin/init.sh` → Step 5 `rewrite-docs.sh` (EXACT command above) → Step 6 `git status` + `git diff --stat` → Step 7 build verification (run web + Android + iOS in PARALLEL via concurrent Bash tool calls) → Step 8 `/feature add` loop → Step 9 final report.",
    "4. For Step 8 (the `/feature add` loop), follow this EXACT sequence for each backlog item. Do NOT deviate — the forge verifies spec-file-vs-matrix consistency at the end of Step 8 and will halt the run on any drift.",
    "",
    "   For each slug in IDEA.md's `features:` frontmatter list (in order):",
    "",
    "   a. Read `specs/features/_template.md` via the Read tool to see the canonical spec shape.",
    "   b. Draft the spec for <slug>: fill in Description, API, Web Implementation, Mobile Implementation, Status (all boxes `- [ ]`).",
    "   c. Write the file to `specs/features/<slug>.md` via the Write tool. Body >= ~800 bytes of real content, not a 3-line stub.",
    "   d. **Immediately call Read** on the file to verify it landed on disk. If Read fails or returns a file <500 bytes, halt with a descriptive error.",
    "   e. **ONLY THEN** update `PLAN.md`: flip the matrix row for <slug> so the `Spec` column changes from `🔲` to `✅`. Leave the other columns `🔲`.",
    "   f. Move to the next slug.",
    "",
    "5. After the Step 8 loop, run this end-of-Step-8 verification sweep:",
    "",
    "   a. `ls specs/features/*.md` (strip `_template.md`).",
    "   b. `grep -E '^\\| [a-z0-9-]+ +\\|.*\\| ✅ +\\|' PLAN.md` — rows with `Spec ✅`.",
    "   c. Cross-reference. Any `Spec ✅` row without a file OR any file without a matching row → halt with a clear error quoting the mismatch.",
    "",
    "6. Post-bootstrap hardening (run AFTER Step 8, BEFORE the final report):",
    "",
    "   a. **`global-error.tsx`**: if `web/src/app/global-error.tsx` does NOT exist,",
    '      create it with `"use client"`, its own `<html>/<body>` tags, an `error`',
    "      prop, and a `reset()` button. No context-provider dependencies. Next.js 16",
    "      prerender crashes without this file.",
    "   b. **Clerk sign-in catch-all**: if a `sign-in/page.tsx` exists without a",
    "      `[[...rest]]` wrapper directory, move it to `sign-in/[[...rest]]/page.tsx`.",
    "      Same for `sign-up` if present. Clerk needs catch-all for multi-step flows.",
    "   c. **`.env.example` audit**: grep all `process.env.*` references in `web/src/`.",
    "      For each variable NOT already listed in `web/.env.example`, add a commented",
    "      entry with the variable name and a short note on where to get the value.",
    "   d. **`proxy.ts` function declaration**: read `web/src/proxy.ts`. If the",
    "      `proxy` export uses `export const proxy = clerkMiddleware(...)` (a bare",
    "      assignment from a library call), rewrite it as a function expression:",
    "      `export const proxy = clerkMiddleware((auth, request) => { ... })`. Next.js 16",
    "      requires the proxy export to be a recognizable function — a bare assigned",
    "      value silently fails and `/` returns 404.",
    "   e. **Mobile package directory sanity check**: Kotlin packages use dotted notation",
    "      (e.g. `com.priorli.myapp`) but on disk must be NESTED directories",
    "      (`com/priorli/myapp/` — 3 folders, not 1). Run:",
    "        `find mobile -type d -maxdepth 8 | grep -E '[\\\\.]' | grep -v 'mobile/iosApp\\\\|\\\\.gradle\\\\|build/'`",
    "      If this finds any directory with a literal `\\` or a `.` in its name under",
    "      `mobile/shared/src/*/kotlin/` or `mobile/composeApp/src/*/kotlin/`, you have",
    "      the escape-slash bug (e.g. a single folder named `com\\/priorli\\/myapp`).",
    "      Halt with a descriptive error showing the offending paths.",
    "   f. **`prisma db push`**: if a DATABASE_URL is available in `.env.local`,",
    "      run `cd web && npx prisma db push` to sync the schema. If not, skip —",
    "      the user will run it themselves.",
    "",
    "7. Do NOT commit. Do NOT touch `CLAUDE.md`, `LESSONS.md`, `bin/init.sh`, `.claude/skills/**`, or `IDEA.md`.",
    "",
    "Start with Step 1 now.",
  ].join("\n");
}

export function buildSeedDemoPrompt(): string {
  return FORGE_PROMPT_PREAMBLE + [
    "Run /seed-demo.",
    "",
    "The downstream project has just been bootstrapped by /init-app. The",
    "Prisma schema is at `web/prisma/schema.prisma`, the seed stub is at",
    "`web/prisma/seed.ts`, and the package.json is at `web/package.json`.",
    "",
    "Follow the skill's steps: read the schema, overwrite the seed stub",
    "with a Faker-powered generator scoped to DEMO_USER_ID, patch",
    "package.json (add @faker-js/faker + prisma seed config + db:seed",
    "script), run `bun install`, and — if DATABASE_URL is set in",
    "`web/.env.local` or `web/.env` — run `bun run db:seed` to populate",
    "the DB.",
    "",
    "This is a non-fatal postlude. If DATABASE_URL is missing, generate",
    "the files but do NOT fail the session — just print the command the",
    "user should run themselves.",
    "",
    "Do NOT touch source files outside web/prisma/seed.ts and",
    "web/package.json. Do NOT create Attachments or call any object",
    "storage. Do NOT modify CLAUDE.md, README.md, or any other docs.",
    "",
    "Start with Step 1 now.",
  ].join("\n");
}

export function buildFeatureContinuePrompt(
  slug: string,
  idx: number,
  total: number,
  platformTarget: "web" | "mobile" | "all" = "all",
  namespace: string = "com.example.app",
): string {
  const includeWeb = platformTarget === "web" || platformTarget === "all";
  const includeMobile = platformTarget === "mobile" || platformTarget === "all";
  // Kotlin packages use dotted notation (com.priorli.myapp) but on disk must
  // be nested directories (com/priorli/myapp). Convert here so the agent
  // gets an unambiguous path instead of a <namespace> placeholder it might
  // misinterpret (a prior forge run once created a single literal directory
  // named `com\/priorli\/myapp` — see LESSONS.md "Forge-discovered gotchas").
  const namespacePath = namespace.replace(/\./g, "/");

  const targetLabel =
    platformTarget === "web"
      ? "API + Web only (mobile deferred)"
      : platformTarget === "mobile"
        ? "API + Mobile only (web deferred)"
        : "all platforms (API + Web + Mobile)";

  // Build the numbered execution steps dynamically
  const steps: string[] = [];
  let stepNum = 1;

  // Step: read spec (always)
  steps.push(
    `${stepNum}. Read \`specs/features/${slug}.md\` to understand the feature's intent,`,
    "   API contract, and per-platform implementation notes.",
  );
  stepNum++;

  // Step: API layer (always)
  steps.push(
    `${stepNum}. Implement the **API layer** first: create new route(s) under`,
    "   `web/src/app/api/v1/<resource>/route.ts` with zod schemas inline.",
    "   Response shape is `{ data: T } | { error: { code, message } }` per",
    "   PLAN.md architecture principle #5. Every route calls `requireUser()`",
    "   from `web/src/lib/auth.ts` at the top. If new Prisma models are needed,",
    "   add them to `web/prisma/schema.prisma` and run `bunx prisma migrate dev`.",
  );
  stepNum++;

  // Step: Web layer (if target includes web)
  if (includeWeb) {
    steps.push(
      `${stepNum}. Implement the **Web layer**: new page(s) under \`web/src/app/[locale]/\``,
      "   following the existing `items` feature as the canonical pattern. Pages",
      "   fetch data via `fetch('/api/v1/...')` — never direct Prisma calls.",
    );
    stepNum++;
  }

  // Step: Mobile layers (if target includes mobile)
  if (includeMobile) {
    steps.push(
      `${stepNum}. Implement the **Mobile (Android) layer**: new Clean Architecture module`,
      `   at \`mobile/shared/src/commonMain/kotlin/${namespacePath}/domain/${slug}/\``,
      `   (interfaces + use cases) + \`mobile/shared/src/commonMain/kotlin/${namespacePath}/data/${slug}/\``,
      `   (DTOs + repo impl) + \`mobile/composeApp/src/commonMain/kotlin/${namespacePath}/feature/${slug}/\``,
      "   (Compose screens + viewmodels).",
      `   **Critical:** the directory \`${namespacePath}\` is NESTED — each segment (\`${namespacePath.split("/").join("\`, \`")}\`) is its own folder. NEVER create a single directory with dots or slashes in its name (e.g. do NOT create \`${namespace}\` or \`${namespacePath.replace(/\//g, "\\\\/")}\` as one folder).`,
    );
    stepNum++;
    steps.push(
      `${stepNum}. **Mobile (iOS) comes for free from commonMain** — verify it still builds.`,
    );
    stepNum++;
  }

  // Build verification instructions — only for targeted platforms
  const verifyLines: string[] = [];
  if (includeWeb) {
    verifyLines.push("- **Web**: `cd web && bun run build`");
  }
  if (includeMobile) {
    verifyLines.push(
      "- **Android**: `cd mobile && ./gradlew :composeApp:assembleDebug`",
      "- **iOS**: `cd mobile && ./gradlew :composeApp:linkDebugFrameworkIosSimulatorArm64`",
    );
  }

  // Checkbox/matrix instructions — only flip implemented platforms
  const checkboxNote =
    platformTarget === "all"
      ? "flip each implemented checkbox from `- [ ]` to `- [x]`."
      : platformTarget === "web"
        ? "flip the API and Web checkboxes to `- [x]`. Leave Mobile Android and Mobile iOS as `- [ ]`."
        : "flip the API, Mobile Android, and Mobile iOS checkboxes to `- [x]`. Leave Web as `- [ ]`.";

  const matrixNote =
    platformTarget === "all"
      ? `flip the matrix row columns for \`${slug}\` from 🔲 to ✅.`
      : platformTarget === "web"
        ? `flip API and Web columns for \`${slug}\` to ✅. Leave Android and iOS as 🔲.`
        : `flip API, Android, and iOS columns for \`${slug}\` to ✅. Leave Web as 🔲.`;

  return FORGE_PROMPT_PREAMBLE + [
    `Run /feature continue ${slug}.`,
    "",
    `You are implementing feature ${idx} of ${total} in this forge session.`,
    `Platform target: **${targetLabel}**.`,
    `The spec at \`specs/features/${slug}.md\` is drafted but the`,
    "implementation checkboxes are currently unchecked. Your job is to",
    `implement the feature for the targeted platform(s).`,
    "",
    "Execution:",
    "",
    ...steps,
    "",
    "After each platform, run the build verification for that platform:",
    "",
    ...verifyLines,
    "",
    "Do NOT move to the next platform until the current one builds green.",
    "",
    "When complete, update both:",
    "",
    `- \`specs/features/${slug}.md\` — ${checkboxNote}`,
    `- \`PLAN.md\` — ${matrixNote}`,
    "",
    "Constraints:",
    "",
    "- **One feature per run.** Do NOT touch other features' specs or code.",
    "- **Do NOT commit.**",
    "- Do NOT re-run `bin/init.sh` or `rewrite-docs.sh`.",
    "- Do NOT modify `IDEA.md`, `CLAUDE.md`, `README.md`, `LESSONS.md`, or",
    "  `.claude/skills/**`.",
    platformTarget !== "all"
      ? `- **Do NOT implement the ${platformTarget === "web" ? "mobile" : "web"} layer** — it is deferred. Only implement the targeted platform(s).`
      : "",
    "- **`.env.example` maintenance**: if your implementation adds a new",
    "  `process.env.*` variable (e.g., an external API key, a service URL),",
    "  add a commented entry to `web/.env.example` with the variable name",
    "  and a short note on where to get the value. Missing env vars cause",
    "  silent 500s with no error message — keeping `.env.example` complete",
    "  prevents this.",
    "",
    "Start with Step 1 of the /feature continue workflow now.",
  ].filter(Boolean).join("\n");
}

export function buildQaTestPrompt(): string {
  return FORGE_PROMPT_PREAMBLE + [
    "Run browser-based QA tests against the web app using Playwright.",
    "",
    "You are executing the /qa skill in a Triplane Forge session. The app",
    "has been built and verified. Your job is to run the QA test scenarios",
    "against the live web dev server and report pass/fail results.",
    "",
    "## Step 1 — Locate test scenarios",
    "",
    "Read `PLAN_REVIEW.md` at the repo root. Look for `## QA review` and its",
    "per-feature subsections. Each subsection has a feature name, golden path",
    "scenario, edge case 1, edge case 2, and acceptance criterion.",
    "",
    "If PLAN_REVIEW.md doesn't exist or has no QA section, fall back to reading",
    "each `specs/features/*.md` (excluding `_template.md`). Synthesize scenarios",
    "from the Description and API sections: golden path = primary workflow,",
    "edge case 1 = empty/missing data, edge case 2 = boundary condition.",
    "",
    "If neither source yields scenarios, report that no scenarios were found and",
    "recommend running `/plan-qa-review` first. Do NOT fail — just skip testing.",
    "",
    "## Step 2 — Install Playwright",
    "",
    "```bash",
    "cd web && bun add -D @playwright/test && npx playwright install chromium",
    "```",
    "",
    "If installation fails, report the error and stop.",
    "",
    "## Step 3 — Write playwright.config.ts",
    "",
    "Write `web/playwright.config.ts` with:",
    "- testDir: `./e2e`",
    "- timeout: 30000",
    "- retries: 0",
    "- baseURL from `process.env.BASE_URL || 'http://localhost:3000'`",
    "- screenshot: `only-on-failure`",
    "- trace: `retain-on-failure`",
    "- chromium-only project",
    "- outputDir: `./e2e/test-results`",
    "",
    "## Step 4 — Generate test files",
    "",
    "For each feature, write `web/e2e/<feature-slug>.spec.ts`.",
    "",
    "Rules:",
    "- Use `getByRole`, `getByText`, `getByLabel` — never CSS selectors",
    "- Each test starts from `page.goto()` — no shared state",
    "- Auth-gated pages: detect `/sign-in` redirect, call `test.skip('requires Clerk auth')`",
    "- Data-dependent: check if content exists, call `test.skip('needs /seed-demo')` if absent",
    "- Never use `page.waitForTimeout()` — use `expect(locator).toBeVisible()`",
    "",
    "## Step 5 — Start or discover dev server",
    "",
    "Check if a dev server is running:",
    "```bash",
    "curl -s -o /dev/null -w '%{http_code}' http://localhost:3000",
    "```",
    "",
    "If not responding, start one:",
    "```bash",
    "cd web && bun run dev &",
    "```",
    "Watch stdout for `http://localhost:XXXX` (up to 30s).",
    "",
    "## Step 6 — Run tests",
    "",
    "```bash",
    "cd web && BASE_URL=<url> npx playwright test --reporter=list",
    "```",
    "",
    "## Step 7 — Report results",
    "",
    "Parse the output. Report per-feature: [PASS]/[FAIL]/[SKIP] per scenario,",
    "error messages on failure, screenshot paths. Summary: X passed, Y failed,",
    "Z skipped.",
    "",
    "## Step 8 — Cleanup",
    "",
    "If you started the dev server, kill it: `kill %1 2>/dev/null || true`",
    "",
    "## Forge-specific constraints",
    "",
    "- Do NOT enter the fix loop (Step 9 of the standalone skill). In the forge",
    "  pipeline, QA is informational only — report results and move on.",
    "- Do NOT commit any files.",
    "- Test files are disposable — they will be gitignored.",
    "- Keep cost low: if scenarios are straightforward, write simple tests.",
    "",
    "Start with Step 1 now.",
  ].join("\n");
}

export function buildDesignStudyPrompt(inputs: DesignStudyInputs): string {
  const sourcesDir = "design/studies/pending/sources";
  const imageList = inputs.imageNames.length > 0
    ? inputs.imageNames.map((n) => `  - ${sourcesDir}/${n}`).join("\n")
    : "  (none — URL-only study)";
  const urlList = inputs.urls.length > 0
    ? inputs.urls.map((u) => `  - ${u}`).join("\n")
    : "  (none)";
  const prosePrompt = inputs.prompt.trim().length > 0
    ? inputs.prompt.trim()
    : "(no prose prompt provided — infer intent from the references)";

  return FORGE_PROMPT_PREAMBLE + [
    "You are running a design study for a Triplane project. A Forge user has",
    "dropped reference images, URLs, and a prose prompt into the worktree.",
    "Use the `/design-study` skill — read `.claude/skills/design-study/SKILL.md`",
    "to load its full instructions — and produce a `DESIGN_STUDY.md` report.",
    "",
    "## Inputs",
    "",
    "Reference images (already written to the worktree):",
    imageList,
    "",
    "Reference URLs (capture screenshots via Playwright if available, otherwise",
    "skip with a note; do NOT fail if Playwright isn't installed):",
    urlList,
    "",
    "Prose prompt (the user's description of the desired vibe / direction):",
    "",
    prosePrompt,
    "",
    "## Run mode",
    "",
    "**Read-only.** Do NOT apply any proposed changes. Do NOT edit",
    "`design/tokens.json`, `design/tokens.schema.json`, `bin/design-tokens.sh`,",
    "or any component file. The user will decide whether to apply via a later",
    "step (not in this phase).",
    "",
    "## Output location",
    "",
    "Write the report to `design/studies/pending/DESIGN_STUDY.md` (the forge",
    "runner will rename `pending/` to a timestamped directory after you",
    "finish). Source images are already in `pending/sources/`.",
    "",
    "Include the sections the skill requires: Summary, Token deltas (with",
    "confidence notes on OKLch estimates — ±0.02 L, ±5° h), Schema extensions",
    "(if references imply tokens the bespoke schema can't express), Component",
    "gaps, and Accessibility spot-checks.",
    "",
    "Start now by reading `.claude/skills/design-study/SKILL.md` and the inputs",
    "under `design/studies/pending/sources/`.",
  ].join("\n");
}

function buildResumePrompt(): string {
  return FORGE_PROMPT_PREAMBLE + [
    "You hit an error mid-run earlier while executing `/init-app` in this",
    "worktree. Please continue from exactly where you stopped:",
    "",
    "1. Run `git status` and `git diff --stat` to see which files you already",
    "   modified. This is ground truth for what's done.",
    "2. Read any specs you already drafted under `specs/features/` to confirm",
    "   which `/feature add` loop iteration you were on.",
    "3. Pick up from whichever `/init-app` step was in progress. Do NOT redo",
    "   work that's already in the working tree.",
    "4. Run through the remaining steps to completion.",
    "",
    "Do NOT re-run `bin/init.sh` or `rewrite-docs.sh` if their effects are",
    "already visible in `git status`. Do NOT `git commit` or `git reset`.",
    "",
    "Start by running `git status` and telling me what you find.",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Resume worker — standalone, not part of the phase chain.
// ---------------------------------------------------------------------------

export interface StartResumeWorkerArgs {
  sessionId: string;
  worktreePath: string;
}

/**
 * Resume a previously-failed forge session by running `claude -c` inside
 * the existing worktree with a continuation prompt. The prior conversation
 * state is loaded from disk by the CLI.
 *
 * Fire-and-forget. Returns the abort controller for the /resume route to
 * wire up mid-run aborts.
 *
 * CLI-only: the SDK runner throws on `resume: true`. The /resume route
 * validates `FORGE_USE_SDK` is unset before calling here.
 */
export function startResumeWorker(args: StartResumeWorkerArgs): AbortController {
  const abortController = new AbortController();
  sessionStore.setAbortController(args.sessionId, abortController);
  sessionStore.setStatus(args.sessionId, "bootstrapping");

  const onApproval = async (req: ApprovalRequest): Promise<ApprovalDecision> => {
    const approvalId = randomUUID();
    const decision = await new Promise<{ approved: boolean; note?: string }>((resolve) => {
      sessionStore.registerApproval(args.sessionId, {
        approvalId,
        title: req.title ?? req.displayName ?? `Run ${req.toolName}`,
        body: req.decisionReason ?? JSON.stringify(req.input, null, 2),
        resolve,
      });
      sessionStore.appendEvent(args.sessionId, "approval_request", {
        approvalId,
        toolName: req.toolName,
        title: req.title,
        displayName: req.displayName,
        input: req.input,
        blockedPath: req.blockedPath,
        decisionReason: req.decisionReason,
      });
      sessionStore.setStatus(args.sessionId, "awaiting_approval");
    });
    sessionStore.setStatus(args.sessionId, "bootstrapping");
    return decision.approved
      ? { behavior: "allow" }
      : {
          behavior: "deny",
          message:
            decision.note && decision.note.length > 0
              ? `Rejected by user: ${decision.note}`
              : "Rejected by user via forge approval gate.",
        };
  };

  void (async () => {
    try {
      const result = await runAgent({
        cwd: args.worktreePath,
        prompt: buildResumePrompt(),
        sessionId: args.sessionId,
        abortController,
        onApproval,
        permissionMode: "default",
        resume: true,
      });

      if (result.completed) {
        sessionStore.setStatus(args.sessionId, "ready");
      } else {
        sessionStore.fail(
          args.sessionId,
          result.errorMessage ?? "Resume did not complete",
        );
      }
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      sessionStore.fail(args.sessionId, message);
    } finally {
      sessionStore.setAbortController(args.sessionId, null);
    }
  })();

  return abortController;
}
